### PR TITLE
Move to new project system and multitarget to netcoreapp2.0

### PR DESCRIPTION
**Pull request by bording**
This will let you run benchmarks on .NET Core as well!

It also moves to the latest BenchmarkDotNet.

Several files had mixed line endings, so those all got switched to CRLF as part of this.

### CODE REVIEW

**Comment by bording** [comment]
I also removed the extra x86/x64 solution configurations since they aren't likely to work well with .NET Core anyway.

If you want to test 32bit, it would be best to add an additional 32bit .NET Framework job to the benchmark.

**Comment by bording** [comment]
Oh, and as mentioned here http://benchmarkdotnet.org/Configs/Toolchains.htm

If you want to run .NET Core jobs, it's best to run the netcoreapp2.0 host because it will default to netcoreapp1.1 if you try to run it from net461.

**Comment by bording** [comment]
Just bumped up to the latest BenchmarkDotNet release.

**Comment by danielmarbach** [comment]
Thanks

**Pull request merged**
